GET http://localhost:5000/auth/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpeXVzaG1pc2hyYTk2NUBnbWFpbC5jb20iLCJpZCI6IjY0M2ZlN2Y4ZjQwOTE3ZTYxMjk2YzcwOSIsImlhdCI6MTY4MTkxMDg4MSwiZXhwIjoxNjg0NTAyODgxfQ.yafMIvLueorfRYG3i0tWssU4fbY41ELbxsG59cbTe88

###

GET http://localhost:5000/clips/643fe7f8f40917e61296c709/6441115ec58ba88b05d889b4/get-collaborators HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpeXVzaG1pc2hyYTk2NUBnbWFpbC5jb20iLCJpZCI6IjY0M2ZlN2Y4ZjQwOTE3ZTYxMjk2YzcwOSIsImlhdCI6MTY4MTkxMDg4MSwiZXhwIjoxNjg0NTAyODgxfQ.yafMIvLueorfRYG3i0tWssU4fbY41ELbxsG59cbTe88

###

POST /auth/login HTTP/1.1
Host: localhost:5000
Content-Length: 253
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

piyushmishra965@gmail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

123456789
------WebKitFormBoundary7MA4YWxkTrZu0gW--